Annotation figs
MorrellLAB/sequence_handling pull request #50
Opened 2020-10-21 03:02 UTC by EDitt

Additions to Create_HC_Subset handler to generate graphs showing distributions of variants that passed/didn't pass filtering

2020-10-21 03:04 UTC, EDitt commented
@ChaochihL When I added variables to be exported by sequence handling to the Create HC Subset function, I also noticed a couple variables that appeared to be missing, so I added them. Just wanted to point out so you could double-check that.

2020-10-27 22:57 UTC, ChaochihL requested changes
Thanks for adding these scripts! I included a couple suggested modifications and one feature request.

2020-10-27 22:57 UTC, ChaochihL commented on Handlers/Create_HC_Subset.sh
> +    source "${seqhand}/HelperScripts/graph_annotations.sh"
Just wanted to check if it has been confirmed that the GATK syntax is the same for GATK v3.8.0 and GATK v4. If not, the v3 documentation has been archived and is difficult to search through, so I would suggest holding off on adding it to the `Create_HC_Subset_GATK3` function until we are sure this syntax is compatible with v3.

2020-10-27 22:57 UTC, ChaochihL commented on HelperScripts/graph_annotations.sh
> +    bedtools random -l ${gen_len} -n ${gen_num} -seed 65 \
I suggest adding this bedtools dependency to the `declare -a Create_HC_Subset_Dependencies=(parallel vcftools R vcfintersect python3 bcftools)` in line 10 of the `Create_HC_Subset.sh` script.

2020-10-27 22:57 UTC, ChaochihL commented on HelperScripts/graph_annotations.R
> +library(gridExtra)
R libraries is a frequent place for pipelines to error out. This is more a feature request (since this script doesn't exist yet for sequence_handling R scripts). Could you add a script that checks if R libraries are installed and if they are not installed, install them? This script should be called in the `sequence_handling` script as part of the checks in this handler (prior to when jobs get submitted). You can use this script as a guideline: https://github.com/ANGSD-wrapper/angsd-wrapper/blob/master/Wrappers/startShiny.R

2020-12-17 20:06 UTC, EDitt commented on Handlers/Create_HC_Subset.sh
> +    source "${seqhand}/HelperScripts/graph_annotations.sh"
I will remove this from the Create HC Subset GATK3 function here. Do you also want me to remove the variable assignments for it (lines 269-271 in Create_HC_Subset.sh, and lines 702 & 712 in sequnce_handling) or leave those as is to make it easier to add this functionality back in later if desired?

2020-12-18 06:25 UTC, EDitt commented on HelperScripts/graph_annotations.R
> +library(gridExtra)
@ChaochihL I saw there is a "install_dependencies.R" script that says it's untested, but I'm currently testing it and plan to incorporate it to resolve this. The one thing I don't exactly know how to handle is how to specify the location to install R packages. I could have a statement in `sequence_handling` that checks if an R_LIBS_USER variable is defined in the config and if not, define it based on the default location?

2020-12-23 20:37 UTC, ChaochihL commented on HelperScripts/graph_annotations.R
> +library(gridExtra)
discussed this issue on Slack

2020-12-23 20:38 UTC, merged